### ISSUE TITLE
MonitorCard在一开始只有少量数据的时候

### ISSUE THREAD

**Issue by nodgd** [FeelVeryZan/NRFUART#15]
少量数据的时候，横坐标会拉伸得非常宽，这样非常丑。我们可以在图上，加横竖两条颜色设置为纯透明的线段。横线段就是从目前能够显示的左端点，到左端点+len（目前len=30）的位置；竖线就从0到256。

**Comment by CudraniaE** [comment]
Cue觉得每次还要更新那条假线十分的烦，明明今天可以写完这个他准备推到之后再写

**Comment by nodgd** [comment]
楼上的你你你你你你你你你你你你你你你你你你你先把头像换了

**Comment by CudraniaE** [comment]
Solved
